export const featuredArtworks = [
  {
    id: 'mock-1',
    slug: 'night-signal',
    title: 'Night Signal',
    author_name: 'Raze',
    location_name: 'Berlin, Germany',
    created_year: '2024',
    style: 'Wildstyle',
    description: 'Контрастная композиция с индустриальными формами, резким светом и ритмикой ночного города.',
    image_url: '',
    tags: ['night', 'signal', 'wildstyle'],
    status: 'approved',
    locale: 'ru',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    slug: 'concrete-bloom',
    title: 'Concrete Bloom',
    author_name: 'Nila',
    location_name: 'Rotterdam, Netherlands',
    created_year: '2025',
    style: 'Abstract Lettering',
    description: 'Смешение жёсткой типографики и органических форм на серой городской поверхности.',
    image_url: '',
    tags: ['abstract', 'lettering', 'bloom'],
    status: 'approved',
    locale: 'ru',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    slug: 'transit-echo',
    title: 'Transit Echo',
    author_name: 'Mirok',
    location_name: 'Warsaw, Poland',
    created_year: '2023',
    style: 'Character',
    description: 'Работа о движении, памяти маршрутов и визуальном шуме современного мегаполиса.',
    image_url: '',
    tags: ['character', 'transit', 'echo'],
    status: 'approved',
    locale: 'ru',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    slug: 'wall-script',
    title: 'Wall Script',
    author_name: 'Aven',
    location_name: 'Antwerp, Belgium',
    created_year: '2022',
    style: 'Lettering',
    description: 'Выверенная работа с плотной буквой, тенью и спокойным ритмом индустриального фасада.',
    image_url: '',
    tags: ['lettering', 'wall', 'script'],
    status: 'approved',
    locale: 'en',
    created_at: new Date().toISOString(),
  },
];

export const artists = [
  {
    id: 'artist-1',
    display_name: 'Raze',
    city: 'Berlin',
    style: 'Wildstyle / Letterform',
    bio: 'Работает с тяжёлой типографикой и архитектурной логикой городских поверхностей.',
  },
  {
    id: 'artist-2',
    display_name: 'Nila',
    city: 'Rotterdam',
    style: 'Abstract / Mural',
    bio: 'Соединяет цвет, форму и ритм стен в масштабных живописных работах.',
  },
  {
    id: 'artist-3',
    display_name: 'Mirok',
    city: 'Warsaw',
    style: 'Character / Narrative',
    bio: 'Фокусируется на персонажах, сюжетных композициях и городской памяти.',
  },
];

export const historyEntries = [
  {
    id: 'hist-1',
    locale: 'ru',
    era_label: 'Origins',
    year_label: '1960s',
    title: 'Ранние городские надписи',
    body: 'Появление заметных подписей и первых повторяющихся имён в городской среде. Этот этап важен как визуальная предпосылка культуры tag.',
    accent: 'Street marks',
    sort_order: 1,
    is_published: true,
  },
  {
    id: 'hist-2',
    locale: 'ru',
    era_label: 'Tagging',
    year_label: '1970s',
    title: 'Рост tagging culture',
    body: 'Формирование узнаваемой практики tag, распространение имён через транспортную сеть и появление визуальной конкуренции между авторами.',
    accent: 'Transit lines',
    sort_order: 2,
    is_published: true,
  },
  {
    id: 'hist-3',
    locale: 'ru',
    era_label: 'Global scene',
    year_label: '1980s',
    title: 'Глобальное внимание',
    body: 'Граффити становится заметной частью уличной культуры, попадает в медиа, музыкальную среду и выставочные пространства.',
    accent: 'Media shift',
    sort_order: 3,
    is_published: true,
  },
  {
    id: 'hist-4',
    locale: 'ru',
    era_label: 'Archive age',
    year_label: '2000s+',
    title: 'Архивирование и фестивали',
    body: 'Появляются фестивали, кураторские площадки, цифровые коллекции и исследовательские проекты, фиксирующие граффити как культурное наследие.',
    accent: 'Digital archive',
    sort_order: 4,
    is_published: true,
  },
  {
    id: 'hist-en-1',
    locale: 'en',
    era_label: 'Origins',
    year_label: '1960s',
    title: 'Early urban markings',
    body: 'Visible signatures and recurring names begin to appear in the city, laying the groundwork for later tagging culture.',
    accent: 'Street marks',
    sort_order: 1,
    is_published: true,
  },
  {
    id: 'hist-en-2',
    locale: 'en',
    era_label: 'Tagging',
    year_label: '1970s',
    title: 'The rise of tagging culture',
    body: 'Tags spread through transit lines and the city becomes a surface for competition, rhythm, and visibility.',
    accent: 'Transit lines',
    sort_order: 2,
    is_published: true,
  },
  {
    id: 'hist-en-3',
    locale: 'en',
    era_label: 'Global scene',
    year_label: '1980s',
    title: 'Global attention',
    body: 'Graffiti enters media, music, and exhibition spaces, becoming a visible branch of contemporary street culture.',
    accent: 'Media shift',
    sort_order: 3,
    is_published: true,
  },
  {
    id: 'hist-en-4',
    locale: 'en',
    era_label: 'Archive age',
    year_label: '2000s+',
    title: 'Archives and festivals',
    body: 'Festivals, curated spaces, and digital collections begin documenting graffiti as both a living scene and cultural memory.',
    accent: 'Digital archive',
    sort_order: 4,
    is_published: true,
  },
];

export const newsPosts = [
  {
    id: 'news-1',
    locale: 'ru',
    slug: 'why-archive-matters',
    category: 'Editorial',
    title: 'Почему архивные платформы важны для граффити-культуры',
    excerpt: 'Цифровой архив сохраняет не только изображение, но и контекст: автора, место, время и культурную связь между поколениями.',
    body: 'Архивная платформа помогает удерживать граффити вне логики случайного исчезновения. Когда работа получает карточку, описание, автора и место, она превращается из разовой городской поверхности в часть культурной памяти. Для WALLTRACE это ключевая идея: не просто показывать работы, а выстраивать связи между авторами, эпохами и городами.',
    cover_image_url: '',
    is_published: true,
    published_at: '2026-02-15T10:00:00.000Z',
  },
  {
    id: 'news-2',
    locale: 'ru',
    slug: 'festival-format-europe',
    category: 'News',
    title: 'Фестивальный формат и новая публичность граффити в Европе',
    excerpt: 'Легальные стены, кураторские подборки и открытые сессии меняют способ взаимодействия зрителя с уличным искусством.',
    body: 'Современные фестивали превращают граффити в публичный диалог между художником, городом и аудиторией. Для архивной платформы это особенно важно: событие не заканчивается стеной, а продолжается в документации, интервью, карточках работ и медиаматериалах.',
    cover_image_url: '',
    is_published: true,
    published_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'news-en-1',
    locale: 'en',
    slug: 'why-archive-platforms-matter',
    category: 'Editorial',
    title: 'Why archival platforms matter for graffiti culture',
    excerpt: 'A digital archive preserves more than the image itself: it preserves authorship, location, timing, and continuity.',
    body: 'An archival platform keeps graffiti from disappearing into pure ephemerality. Once a work has a record, metadata, and context, it becomes part of cultural memory rather than only a fleeting urban surface. WALLTRACE is built around that logic.',
    cover_image_url: '',
    is_published: true,
    published_at: '2026-02-15T10:00:00.000Z',
  },
  {
    id: 'news-en-2',
    locale: 'en',
    slug: 'festival-format-europe-en',
    category: 'News',
    title: 'Festival formats and the new public visibility of graffiti in Europe',
    excerpt: 'Legal walls, curated sessions, and open calls are changing how audiences encounter urban art.',
    body: 'Contemporary festivals turn graffiti into a public conversation between artist, city, and audience. For an archive platform, this matters because the event can continue through documentation, artist pages, artwork records, and editorial context.',
    cover_image_url: '',
    is_published: true,
    published_at: '2026-03-01T10:00:00.000Z',
  },
];

export const eventItems = [
  {
    id: 'event-1',
    locale: 'ru',
    slug: 'open-wall-session-rotterdam',
    title: 'Open Wall Session',
    city: 'Rotterdam',
    venue: 'Open Yard',
    summary: 'Открытая сессия для художников и зрителей с кураторским обсуждением работ и их документацией.',
    body: 'Формат открытой стены важен не только как практика создания, но и как точка встречи сообщества. Для WALLTRACE такие события — естественный мост между архивом и живой сценой.',
    starts_at: '2026-04-14T17:00:00.000Z',
    ends_at: '2026-04-14T21:00:00.000Z',
    is_published: true,
  },
  {
    id: 'event-2',
    locale: 'ru',
    slug: 'archive-talk-amsterdam',
    title: 'Archive Talk',
    city: 'Amsterdam',
    venue: 'City Lab',
    summary: 'Публичная дискуссия о документировании граффити и роли цифровых архивов.',
    body: 'Разговор о том, как переводить уличные работы в цифровой формат без потери контекста: места, автора, времени и городской среды.',
    starts_at: '2026-05-28T18:30:00.000Z',
    ends_at: '2026-05-28T20:00:00.000Z',
    is_published: true,
  },
  {
    id: 'event-en-1',
    locale: 'en',
    slug: 'open-wall-session-rotterdam-en',
    title: 'Open Wall Session',
    city: 'Rotterdam',
    venue: 'Open Yard',
    summary: 'An open session for artists and visitors with a curatorial discussion and live documentation.',
    body: 'Open wall formats matter not only as acts of creation, but also as meeting points for scene-building, public dialogue, and future archiving.',
    starts_at: '2026-04-14T17:00:00.000Z',
    ends_at: '2026-04-14T21:00:00.000Z',
    is_published: true,
  },
  {
    id: 'event-en-2',
    locale: 'en',
    slug: 'archive-talk-amsterdam-en',
    title: 'Archive Talk',
    city: 'Amsterdam',
    venue: 'City Lab',
    summary: 'A public talk on documenting graffiti and the role of digital archives.',
    body: 'A conversation on how street works can be translated into digital records without losing the context of place, authorship, time, and urban surface.',
    starts_at: '2026-05-28T18:30:00.000Z',
    ends_at: '2026-05-28T20:00:00.000Z',
    is_published: true,
  },
];
